# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  builConfiguration: 'Release'

steps:
- script: dotnet test
  displayName: run unit test

- script: dotnet build --configuration $(builConfiguration)
  displayName: Build application

- script: docker build -t my-image:v1.0
  displayName: Build image

- script: dotnet push my-image:v1.0
  displayName: push image
